### ISSUE TITLE
configure: error: *** -lrcsc_geom not found! ***

### ISSUE THREAD

**Issue by bestpredicts** [helios-base/helios-base#1]
Below is my machine environment：
ubuntu20.04
rcsssever 16.0
rcssmonitor 16.0
helios-base/librcsc 
helios-base/soccerwindow2-master 

I checked some environments， rcsssever,rcssmonitor,soccerwindow2  can run well.

**Comment by bestpredicts** [comment]
here is error info 
```bash
checking whether g++ supports C++14 features with -std=c++14... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for boostlib >= 1.38.0 (103800)... yes
checking for cos in -lm... yes
checking for deflate in -lz... yes
checking for main in -lrcsc_geom... no
configure: error: *** -lrcsc_geom not found! ***

````

**Comment by hidehisaakiyama** [comment]
The current repository does not support the latest librcsc.
Please wait for a while.

**Comment by NTsering** [comment]
Has this been resolved?

**Comment by hidehisaakiyama** [comment]
Not yet.
I may try a quick fix in the next few weeks, but unfortunately, I don't have enough time to maintain the base code now.

**Comment by bestpredicts** [comment]
any update here?

**Comment by hidehisaakiyama** [comment]
Sorry, not yet.
Hopefully, within next few months.

**Comment by hidehisaakiyama** [comment]
Fixed on master branch.
