### ISSUE TITLE
nobody command

### ISSUE THREAD

**Issue by bestpredicts** [helios-base/helios-base#19]
`HELIOS_base 1: [4815, 0]  WARNING. no body command.
HELIOS_base 1: [4816, 0]  WARNING. no body command.
HELIOS_base 1: [4817, 0]  WARNING. no body command.
HELIOS_base 1: [4818, 0]  WARNING. no body command.
HELIOS_base 1: [4819, 0]  WARNING. no body command.
HELIOS_base 1: [4820, 0]  WARNING. no body command.
HELIOS_base 1: [4821, 0]  WARNING. no body command.
HELIOS_base 1: [4822, 0]  WARNING. no body command.
HELIOS_base 1: [4823, 0]  WARNING. no body command.
HELIOS_base 1: [4824, 0]  WARNING. no body command.
HELIOS_base 1: [4825, 0]  WARNING. no body command.
HELIOS_base 1: [4826, 0]  WARNING. no body command.
HELIOS_base 1: [4827, 0]  WARNING. no body command.
HELIOS_base 1: [4828, 0]  WARNING. no body command.
HELIOS_base 1: [4829, 0]  WARNING. no body command.
HELIOS_base 1: [4830, 0]  WARNING. no body command.
HELIOS_base 1: [4831, 0]  WARNING. no body command.
HELIOS_base 1: [4832, 0]  WARNING. no body command.
HELIOS_base 1: [4833, 0]  WARNING. no body command.
HELIOS_base 1: [4834, 0]  WARNING. no body command.
HELIOS_base 1: [4835, 0]  WARNING. no body command.
HELIOS_base 1: [4836, 0]  WARNING. no body command.
HELIOS_base 1: [4837, 0]  WARNING. no body command.
HELIOS_base 1: [4838, 0]  WARNING. no body command.
HELIOS_base 1: [4839, 0]  WARNING. no body command.
HELIOS_base 1: [4840, 0]  WARNING. no body command.
HELIOS_base 1: [4841, 0]  WARNING. no body command.
HELIOS_base 1: [4842, 0]  WARNING. no body command.
HELIOS_base 1: [4843, 0]  WARNING. no body command.
HELIOS_base 1: [4844, 0]  WARNING. no body command.

`

The goalkeeper does not move at all for some time, and when the opponent is attacking in the penalty area, the goalkeeper does not move.

**Comment by hidehisaakiyama** [comment]
This message means that the goalkeeper did not register any body action commands in these cycles.
If you have modified the code of the goalie, make sure you have registered the action commands correctly.
Or, the sample goalie may not be compatible with recent simulator changes.

Anyway, you need to adapt your move behaviors to the rule of v17 simulator.
If you don't like to do it, use the v16 simulator for the time being.

**Comment by bestpredicts** [comment]
> This message means that the goalkeeper did not register any body action commands in these cycles. If you have modified the code of the goalie, make sure you have registered the action commands correctly. Or, the sample goalie may not be compatible with recent simulator changes.
> 
> Anyway, you need to adapt your move behaviors to the rule of v17 simulator. If you don't like to do it, use the v16 simulator for the time being.

I didn't modify any code

**Comment by hidehisaakiyama** [comment]
I could not reproduce the same situation.
Are you using the master branch of librcsc and helios-base?
And, what version of the simulator are you using?

**Comment by hidehisaakiyama** [comment]
If no more information, this issue will be closed soon.
