### ISSUE TITLE
Error: No intercept evaluator

### ISSUE THREAD

**Issue by CaioSBC** [helios-base/helios-base#32]
Hello,

I downloaded the master branch and compiled with CMake. Everything worked great but, when running a game, the agent with the ball is constantly printing the following error:

```
Helios_base 11: ERROR: no intercept evaluator.
Helios_base 11: ERROR: no intercept evaluator.
Helios_base 11: ERROR: no intercept evaluator.
```

Curiously, this error is not printed when compiling with automake, so the problem might be related to CMake compiling, maybe.

Unfortunately, I couldn't find the source of the issue...

**Comment by hidehisaakiyama** [comment]
Thanks for reporting the problem.
The missing source file has been added to the CMake build target.
Please check the latest master branch.
